version: '3.8'
name: slipstream-stack

x-environment: &environment
    DB_HOST: slipstream-db
    DB_PASSWORD: yoursecretdbpass

services:
    core:
        container_name: Slipstream_core
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - db
        environment:
            <<: *environment
        volumes:
            - ./.env:/var/www/html/.env # .env File
            - ./teststorage/app:/var/www/html/storage/app # App folder
            - ./teststorage/logs:/var/www/html/storage/logs # Logs
        networks:
            - slipstream_network

    db:
        image: mysql:8
        container_name: slipstream-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            <<: *environment
            MYSQL_DATABASE: slipstream
            MYSQL_ROOT_PASSWORD: yoursecretdbpass
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - slipstream_network

volumes:
    shared-tmp:
    dbdata:

networks:
    slipstream_network:
        driver: bridge

